import React, { useMemo } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, StatusBar } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { Iconify } from 'react-native-iconify';
import { useSelector } from 'react-redux';

import { useColors } from '../context/ThemeContext';
import { AppColors } from '../styles/theme';
import Fonts from '../styles/Fonts';
import { wScale, hScale } from '../styles/Scaler';
import Layout from '../styles/Layout';
import { RootState } from '../redux/store';

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: 'By using Toronto, you agree to these Terms of Service. If you do not agree, please discontinue use of the application immediately.',
  },
  {
    title: '2. Use of the Service',
    body: 'You may use Toronto for personal, non-commercial travel planning. You may not use the service to distribute spam, engage in illegal activities, or infringe on others\' rights.',
  },
  {
    title: '3. User Accounts',
    body: 'You are responsible for maintaining the confidentiality of your account credentials. Any activity under your account is your responsibility. Notify us immediately of any unauthorized use.',
  },
  {
    title: '4. Premium Subscription',
    body: 'Premium features are available through a paid subscription. Subscriptions auto-renew unless cancelled at least 24 hours before the renewal date. Refunds are handled per platform policies.',
  },
  {
    title: '5. Content and AI',
    body: 'Route suggestions and recommendations are generated by AI and may not always be accurate. Always verify safety and accessibility of locations before visiting.',
  },
  {
    title: '6. Limitation of Liability',
    body: 'Toronto is provided "as is". We are not liable for any damages arising from use of the app, inaccurate route data, or inability to access the service.',
  },
  {
    title: '7. Changes to Terms',
    body: 'We may update these terms at any time. Continued use after changes constitutes acceptance of the new terms. We will notify you of significant changes via email or in-app notification.',
  },
];

const TermsOfServiceScreen = () => {
  const navigation = useNavigation();
  const colors = useColors();
  const currentTheme = useSelector((s: RootState) => s.Theme.theme);
  const styles = useMemo(() => makeStyles(colors), [colors]);

  return (
    <View style={styles.root}>
      <StatusBar barStyle={currentTheme === 'dark' ? 'light-content' : 'dark-content'} backgroundColor={colors.inputBackground} />
      <View style={styles.header}>
        <TouchableOpacity style={styles.backBtn} onPress={() => navigation.goBack()}>
          <Iconify icon="solar:alt-arrow-left-linear" size={wScale(22)} color={colors.textPrimary} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Terms of Service</Text>
        <View style={{ width: wScale(36) }} />
      </View>

      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}>
        <Text style={styles.lastUpdated}>Last updated: January 2025</Text>
        {SECTIONS.map(s => (
          <View key={s.title} style={styles.section}>
            <Text style={styles.sectionTitle}>{s.title}</Text>
            <Text style={styles.sectionBody}>{s.body}</Text>
          </View>
        ))}
      </ScrollView>
    </View>
  );
};

export default TermsOfServiceScreen;

const makeStyles = (colors: AppColors) => StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: Layout.screenPaddingH, paddingTop: hScale(16), paddingBottom: hScale(14),
    backgroundColor: colors.inputBackground, borderBottomWidth: 1, borderBottomColor: colors.stroke,
  },
  backBtn: { width: wScale(36), height: wScale(36), alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: wScale(17), fontFamily: Fonts.plusJakartaSansBold, color: colors.textPrimary },
  scroll: { padding: Layout.screenPaddingH, paddingBottom: hScale(40) },
  lastUpdated: { fontSize: wScale(12), fontFamily: Fonts.plusJakartaSansRegular, color: colors.textSecondary, marginBottom: hScale(24) },
  section: { marginBottom: hScale(20) },
  sectionTitle: { fontSize: wScale(15), fontFamily: Fonts.plusJakartaSansBold, color: colors.textPrimary, marginBottom: hScale(8) },
  sectionBody: { fontSize: wScale(14), fontFamily: Fonts.plusJakartaSansRegular, color: colors.textSecondary, lineHeight: hScale(22) },
});
